version: "3.7"
services:

  vogon:
	image: digingasu/vogon-backend:latest
    command: python manage.py migrate
    volumes:
      - log-files:/usr/src/app/logs
    ports:
      - "8000:8000"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:11.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:

volumes:
  db-data:
  log-files: