version: "3.7"
services:

  vogon:
    image: digingasu/vogon-backend:staging
    command: python manage.py migrate
    volumes:
      - log-files:/usr/src/app/logs
    ports:
      - "8000:8000"
    networks:
      - backend

  db:
    image: postgres:11.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5444:5432"
networks:
  frontend:
  backend:

volumes:
  db-data:
  log-files:
