version: "3.7"
services:
  vogon:
    build:
        context: .
        dockerfile: Dockerfile-backend
    ports:
      - "8001:8000"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /home/vogon-web/backend/logs:/usr/src/app/logs
      - /home/vogon-web/backend/code/vogon-web:/usr/src/app/host
  db:
    image: postgres:11.6
    ports:
      - "5444:5432"
    env_file:
      - ./config/db.env
    volumes:
      - /home/vogon-web/backend/db:/var/lib/postgresql/data

