version: "3.7"
services:
  vogon:
    build:
        context: .
        dockerfile: Dockerfile-backend
    volumes:
      - log-files:/usr/src/app/logs
      - vogon-data:/usr/src/app/data
    ports:
      - "8001:8000"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /home/tomcat/vogon-web/backend/logs:/usr/src/app/logs
      - /home/tomcat/vogon-web/backend/code:/usr/src/app/host
  db:
    image: postgres:11.6
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/tomcat/vogon-web/backend/db:/var/lib/postgresql/data

