version: "3.7"
services:

  vogon:
    build:
      context: ./vogon-backend
      dockerfile: Dockerfile
    command: python manage.py migrate
    volumes:
      - log-files:/usr/src/app/logs
    ports:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - ./vogon-backend/.env_secrets
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:11.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints: [node.role == manager]

  vogon-client:
    build:
        context: ./vogon-client
        dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - ./vogon-client/.env_secrets
    volumes:
      - vogon-client-vol:/dist
    deploy:
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  vogon-client-vol:
    external: true
  db-data:
  log-files: